name: Sign Apps
on:
  push:
    branches: ["main"]    
  workflow_run:
    workflows: ["Download IPA"]
    types:
      - completed
  workflow_dispatch:
jobs:
  Sign-Apps:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Import Certificate
       run: echo ${{secrets.IMPORT_CERT_SCRIPT}} | base64 -d > Import_Cert.sh && bash Import_Cert.sh ${{secrets.CERT}} ${{secrets.CERT_PASSWORD}}
     - name: Sign Apps
       run: echo ${{secrets.SIGN_SCRIPT}} | base64 -d > Sign.sh && bash Sign.sh
     - name: Git Push
       run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            for IPA in *.ipa; do
            git add "$IPA"
            done
            git commit -m "Signed Apps"
            git push
